hooks:
  - &base
    language: python
    types: [python]
    require_serial: true
  - &mypy
    id: mypy
    name: mypy
    entry: mypy
    <<: *base
  - &flake8
    id: flake8
    name: flake8
    entry: flake8
    <<: *base
  - &isort
    id: isort
    name: isort
    entry: isort
    <<: *base
  - &pytest
    id: pytest
    name: pytest
    entry: pytest
    <<: *base
  - &pytest2
    id: pytest2
    name: pytest2
    entry: pytest2
    <<: *base

repos:
  - repo: local
    hooks:
      - <<: *mypy
        files: ^python_build/
      - <<: *mypy
        name: mypy (py2)
        files: ^python_build/
        args: ['--py2']
      - <<: *flake8
        files: ^python_build/
      - <<: *isort
        files: ^python_build/
        args: ['--check-only', '--diff']
      - <<: *pytest
        files: ^tests/
        args: ['--exitfirst']
      - <<: *pytest2
        files: ^tests/
        args: ['--exitfirst']

