name: checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install mypy
      run: |
        pip install --upgrade pip
        pip install mypy
        mypy --version

    - name: Install dependencies
      run: pip install importlib_metadata packaging

    - name: Run mypy
      run: mypy --python-version ${{ matrix.python }} src/build


  pre-commit: # per https://github.com/pre-commit/action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
