name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ${{ matrix.platform }}-latest
    strategy:
      matrix:
        platform:
        - ubuntu
        - macos
        - windows
        python:
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 2.7
        - pypy3
        - pypy2

    steps:
    - name: setup python for tox
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install tox
      run: python -m pip install tox
    - name: Set up target Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/checkout@v2
    - name: pick environment to run
      run: |
        import subprocess; import json
        major, minor, impl = json.loads(subprocess.check_output(["python", "-c", "import json; import sys; import platform; print(json.dumps([sys.version_info[0], sys.version_info[1], platform.python_implementation()]));"], universal_newlines=True))
        print('::set-env name=TOXENV::' + ("py" if impl == "CPython" else "pypy") + ("{}{}".format(major, minor) if impl == "CPython" else ("3" if major == 3 else "")))
      shell: python
    - name: setup test suite
      run: tox -vv --notest
    - name: run test suite
      run: tox
    - name: rename coverage report file
      run: |
        import os; os.rename('.tox/coverage.{}.xml'.format(os.environ['TOXENV']), '.tox/coverage.xml')
      shell: python
    - name: send coverage report
      uses: codecov/codecov-action@v1
      env:
        PYTHON: ${{ matrix.python }}
      with:
        file: ./.tox/coverage.xml
        flags: tests
        name: ${{ matrix.py }} - ${{ matrix.os }}
